Moved "How To" and other useful documentation in-app
nbgallery/nbgallery pull request #1000
Opened 2024-12-02 15:07 UTC by eldenlord204824

I was unable to really find the documentation referenced in #874. Therefore, as an alternative I have made simple overarching documentation with the ability for enterprises to add there own documentation appended to the end of the initial documentation.

I am open to feedback and additional overarching documentation that may need to be added or an alternative way to approach this issue.

Note: In order to view review documentation remove the conditional in /app/views/docs/notebook_review.slim and use endpoint /docs/notebook_review.

Will close #874

2024-12-03 15:15 UTC, mild-bit requested changes
fix typos and grammatical errors

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +        li <strong>Desciption:</strong> each notebook is required to have a description to help user understand the use of the notebook and the particular how tos of the specific notebook.
Description*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +    p Uploading a noteboook is easy and allows the use of tags to help users find the notebooks that will help the most.
notebook*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +    p Everything need to know about any particular notebook can be found on the page of the notebook itself.
> "Everything _**you**_ need to know ... "

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +    p The various items are pretty self explainitory, including basic notbook information such as the title, owner (and creator if applicable) description, tags, main language of the notebook, star a
self-explanatory*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +    p The various items are pretty self explainitory, including basic notbook information such as the title, owner (and creator if applicable) description, tags, main language of the notebook, star a
notebook*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +      li <strong>Subscribe:</strong> subcribing to a particular notebook gives you the option to recieve update notification on particular notebooks (maybe ones you utilize a lot)
subscribing*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +      li <strong>Subscribe:</strong> subcribing to a particular notebook gives you the option to recieve update notification on particular notebooks (maybe ones you utilize a lot)
receive*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +      li <strong>Comments:</strong> allows you to comment on a particular notebook (a question, general advise, or just a compliment if you like).
advice*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +        li <strong>View Revision History:</strong> this leades you to the changes to notebook and notices about changes (creation, deprecation, and general edits along with who made did it)
leads*

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +        li <strong>View Revision History:</strong> this leades you to the changes to notebook and notices about changes (creation, deprecation, and general edits along with who made did it)
> "... and general edits along with who made **_the changes_**)"

2024-12-03 15:15 UTC, mild-bit commented on app/views/docs/utilizing_notebooks.slim
> +    p What good is having a collection of notebooks if we cannot filter through them to find only the most critical/useful one. Searching is made easy and seemless in NBGallery.
seamless*

2024-12-05 00:09 UTC, ace6150 approved these changes

2024-12-05 13:20 UTC, mild-bit approved these changes

2024-12-06 15:38 UTC, merged