Provide Feedback fix: Made it so fields are hidden when they should be
nbgallery/nbgallery pull request #418
Opened 2021-01-14 18:14 UTC by manfromjupyter

Closes #316

2021-01-15 17:18 UTC, mcrutch commented
HTML and plain text emails are inconsistent:
HTML:
"xxxx provided the following feedback: "This is feedback""
Plain Text:
"xxxx provided the following feedback: This is feedback Additionally, the user indicated that the notebook was run and it was not successful. The user provided the following feedback about what went wrong for them: I am going to say it worked, but leave this filled out"

Workflow; Click Ran it, click it didn't work, fill out the comment for not working, then change the checkbox to it did work.

2021-01-15 17:19 UTC, mcrutch requested changes
Server-side code is inconsistent with how it handles the checkbox being toggled back to Yes it worked after filling in the comment between plain text and HTML emails

2021-01-15 17:22 UTC, manfromjupyter commented
@mcrutch, I'm on it. Ill be sure to fix those emails

2021-01-20 17:54 UTC, manfromjupyter commented
Made them consistent and while was at it improved the verbiage, spacing, etc. Tested for when notebook was not run, run and no mention of broken, run and labeled broken, and run and labeled as not broken. Good to go on my end

2021-01-21 11:53 UTC, mcrutch requested changes
See comment in code, applies to both text and HTML emails.

2021-01-21 11:53 UTC, mcrutch commented on app/views/notebook_mailer/feedback.html.slim
> +-if @feedback.worked == true
You need to check if ran is true as well.
Workflow: Check that you ran it
Check that it didn't work
add feedback for how it didn't work
check that you didn't run it
submit feedback
Email says they reported it didn't work, even though that option was no longer visible on the form.

2021-01-21 11:56 UTC, mcrutch commented
Forgot one other things...check if the org is actually populated before you add the (org) to the email (since you are fixing the views anyway).
    | #{@submitter.name} (#{@submitter.org}) <-- If org is empty, it says `User's Name ()`

2021-01-21 16:01 UTC, manfromjupyter commented
@mcrutch Oh smart, will check for org and create another ticket to correct it for all others. Won't take me terribly long to do. As per the running thing, that is wacky. Will fix it though

2021-01-22 17:04 UTC, manfromjupyter commented
@mcrutch Should be good to go now. Will fix orgs in other emails later. In terms of the different options when submitting feedback, below will include what both html and raw look like and you can see what all of the other sub options look like in the top 5 emails in the fake email thing. Fixed that submission issue of broken and ran feedback when user switches later they didn't even run it.
![html feedback email](https://user-images.githubusercontent.com/51969207/105521458-ecfa7f00-5ca9-11eb-944f-2a74ba2dffea.PNG)
![text feedback email](https://user-images.githubusercontent.com/51969207/105521459-ecfa7f00-5ca9-11eb-9b7d-60beaa31a6f6.PNG)

2021-01-22 17:10 UTC, merged