External Resource Deletion - No longer bootbox alert
nbgallery/nbgallery pull request #852
Opened 2023-05-18 14:11 UTC by manfromjupyter

Closes #182 

1. Made delete external resource dialog follow same format as rest of our product.
2. Final death to bootbox #668.
3. Moved delete external resource JS to an actual JS file to be minified.
4. Made it so viewing delete notebook confirmation and then going to delete resource doesn't cause those addition line items text to appear.

After this we can do out best to look into what extensions people have with the product and can remove the require bootbox.min and additional bootbox CSS if it comes up clear. @mcrutch if you think we're good to do this now though, just let me know.

2023-06-02 14:27 UTC, mcrutch commented on app/assets/javascripts/notebook_actions.js.erb
> +    $('#confirmationModalForm #inAdditionText').addClass('hide').siblings('.additional-confirmation').text('').addClass('hide');
Click to delete external resource
Click Cancel
Click to delete Notebook
Additional Info list is missing in dialog

2023-06-02 14:27 UTC, mcrutch requested changes
See comment about Additional Info

2023-06-07 20:28 UTC, manfromjupyter commented
@mcrutch Fixed both no matter what one confirmation is selected first and made sure to clear the text completely from one to the other.

2023-06-16 11:13 UTC, mcrutch approved these changes

2023-06-16 11:13 UTC, merged